#### Pandas-DataFrame And Series

- Pandas is a powerful Python library used for data manipulation, data cleaning, and data analysis.

- It provides two main data structures:

- Series — a one‑dimensional, array‑like structure.

- DataFrame — a two‑dimensional, table‑like structure with rows and columns.

- A DataFrame can hold different types of data and can be resized.

- Both structures are essential for working with datasets in Python.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\peter\onedrive\pictures\documents\udemy\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\peter\onedrive\pictures\documents\udemy\.venv\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\peter\onedrive\pictures\documents\udemy\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\peter\onedrive\pictures\documents\udemy\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\peter\onedrive\pictures\documents\udemy\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [4]:
## Series
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create Series from Dictionary elements
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
##
dt = [10,20,30,40]
index = ['a','b','c','d']
pd.Series(data, index=index)

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

##### DataFrame

In [8]:
## Dataframe
## Create a Dataframe from a dictionary of List

data = {
    'Name':['Peter','Gacheri','Kasongo'],
    'Age': [30,1,50],
    'City': ['New York','Paris','Nairobi']
}
df = pd.DataFrame(data)
print(df)
print(type(dt))

      Name  Age      City
0    Peter   30  New York
1  Gacheri    1     Paris
2  Kasongo   50   Nairobi
<class 'list'>

In [10]:
## Create a Dataframe  from a List of Dictionaries

data = [
    {'Name':'Peter','Age':32, 'City':'New York'},
    {'Name':'Gacheri','Age':1, 'City':'Paris'},
    {'Name':'Azma', 'Age':30, 'City':'Perth'},
    {'Name': 'Mfalme', 'Age': 56, 'City': 'Capetown'}    
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City
0    Peter   32  New York
1  Gacheri    1     Paris
2     Azma   30     Perth
3   Mfalme   56  Capetown
<class 'pandas.DataFrame'>

In [12]:
## Read Data set using Pandas

dt = pd.read_csv('data.csv')
dt.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [13]:
## Last 10 records
dt.tail(10)

          Date Category  Value   Product  Sales Region
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [15]:
## Acessing Data from DataFrame
df

      Name  Age      City
0    Peter   32  New York
1  Gacheri    1     Paris
2     Azma   30     Perth
3   Mfalme   56  Capetown

In [18]:
df['Name']

0      Peter
1    Gacheri
2       Azma
3     Mfalme
Name: Name, dtype: str

In [ ]:
## Row index
df.loc[0]

Name       Peter
Age           32
City    New York
Name: 0, dtype: object

In [20]:
## Column index
df.iloc[0]

Name       Peter
Age           32
City    New York
Name: 0, dtype: object

In [26]:
## Accessing 1st column
df.iloc[0, 0]

'Peter'

In [31]:
df.iloc[0, 1]

np.int64(32)

In [34]:
##
df.loc[1]

Name    Gacheri
Age           1
City      Paris
Name: 1, dtype: object

In [42]:
df

      Name  Age      City
0    Peter   32  New York
1  Gacheri    1     Paris
2     Azma   30     Perth
3   Mfalme   56  Capetown

In [49]:
#
df['Name']

0      Peter
1    Gacheri
2       Azma
3     Mfalme
Name: Name, dtype: str

In [46]:
import pandas as pd
import numpy as np
df.at[0,'Age']

np.int64(32)

In [48]:
## Accessing a specified element using iat
df.iat[2,2]

'Perth'

#### Data Manipulation with DataFrames

In [52]:
## Data Manipulation
df

## Add a new column
df['Salary']=[50000,60000,70000,80000]
df

      Name  Age      City  Salary
0    Peter   32  New York   50000
1  Gacheri    1     Paris   60000
2     Azma   30     Perth   70000
3   Mfalme   56  Capetown   80000

In [ ]:
## Remove a column
df.drop('Salary', axis=1, inplace=True) ## axis=1 is temporary, while including inplace=True, deletes permanently
df

      Name  Age      City
0    Peter   32  New York
1  Gacheri    1     Paris
2     Azma   30     Perth
3   Mfalme   56  Capetown

In [63]:
## Add age to the column
## In all columns
df['Age']=df['Age']+1
df

      Name  Age      City
0    Peter   33  New York
1  Gacheri    2     Paris
2     Azma   31     Perth
3   Mfalme   57  Capetown

In [ ]:
## Drop based on row
df.drop(0, inplace=True)

In [68]:
df

      Name  Age      City
1  Gacheri    2     Paris
2     Azma   31     Perth
3   Mfalme   57  Capetown

In [71]:
dt.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [75]:
## Statistical Summary

print("Data types:\n,", dt.dtypes)

## Describe the DataFrame
print("Statistical SUmmary:\n", dt.describe())

Data types:
, Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object
Statistical SUmmary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [76]:
## Groupby a column (Category and Value) and perform an aggregation
grouped = dt.groupby('Category')['Value'].mean()
print("Mean value by category:\n", grouped)

Mean value by category:
 Category
A    48.357143
B    44.142857
C    59.842105
Name: Value, dtype: float64

In [77]:
dt.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000